---
title: "Publications"
description: "Articles and conference presentations"
output: distill::distill_article
---

### Selected Articles and Essays


- Khari, M. (forthcoming). *Simulating Strife: Computational Models of Human Conflict*. ABC Journal of Amsterdam Brain and Cognition.
- Khari, M. and Daley, J. (2025, May). *The Four Pillars of Learning: A Teacher’s Guide to Cognitive Success* Mind Brain Ed Think Tank+ of JALT.
- Khari, M. (2024, June). *Spirituality and Cyberspace: The Role of VR in Inducing Spiritual Experiences*. ABC Journal of Amsterdam Brain and Cognition.
- Khari, M. (2024, July). *What We Missed and Why?* Mind Brain Ed Think Tank+ of JALT.
- Khari, M. (2024, February). *The Reading Brain*. Mind Brain Ed Think Tank+ of JALT.
- Khari, M. (2024, January). *Hearts and Minds*. Mind Brain Ed Think Tank+ of JALT.
- Khari, M. (2023, May). *X = Y*. Mind Brain Ed Think Tank+ of JALT.
- Khari, M. (2023, March). *ChatGPT: The Double-Edged Sword of AI Language Models*. Mind Brain Ed Think Tank+ of JALT.
- Khari, M. (2023, January). *Fostering the Prosocial Neural Network Through Gratitude*. Mind Brain Ed Think Tank+ of JALT.
- Khari, M. (2022–2021). Numerous essays and co-authored pieces on **neuroscience**, **storytelling**, **emotional autonomy**, and **language learning**.  


  *See <a href="cv.pdf" target="_blank">full CV (PDF)</a> for complete bibliography.*

---

### Conference Presentations & Webinars

#### 🎥 *on YouTube*

<div style="position:relative; padding-bottom:56.25%; height:0; overflow:hidden; margin-bottom:0.5em;">
  <iframe src="https://www.youtube.com/embed/78VlsATYm-0"
          style="position:absolute; top:0; left:0; width:100%; height:100%;"
          frameborder="0" allowfullscreen>
  </iframe>
</div>
<p style="text-align:center; margin-bottom:2em;"><em>Neuroscience of Stories</em></p>

<div style="position:relative; padding-bottom:56.25%; height:0; overflow:hidden; margin-bottom:0.5em;">
  <iframe src="https://www.youtube.com/embed/_FT-gagz_y4"
          style="position:absolute; top:0; left:0; width:100%; height:100%;"
          frameborder="0" allowfullscreen>
  </iframe>
</div>
<p style="text-align:center; margin-bottom:2em;"><em>The Celestial Openness</em></p>

<div style="position:relative; padding-bottom:56.25%; height:0; overflow:hidden; margin-bottom:0.5em;">
  <iframe src="https://www.youtube.com/embed/fJL85tWtlRs?start=1448"
          style="position:absolute; top:0; left:0; width:100%; height:100%;"
          frameborder="0" allowfullscreen>
  </iframe>
</div>
<p style="text-align:center; margin-bottom:2em;"><em>Embracing the Uncertainty: Fostering Creativity and Responsibility Through Storytelling in Rhizomatic Model of Learning</em></p>

<div style="position:relative; padding-bottom:56.25%; height:0; overflow:hidden; margin-bottom:0.5em;">
  <iframe src="https://www.youtube.com/embed/9wiU38c6wYE?start=3"
          style="position:absolute; top:0; left:0; width:100%; height:100%;"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen>
  </iframe>
</div>
<p style="text-align:center; margin-bottom:2em;"><em>Cultural Context - Putting the Genie of Bias Back in the Bottle</em></p>




---

#### 📣 Other Appearances (selected)

- *Fostering Creativity and Responsibility Through Storytelling in Rhizomatic Learning*, Edulab, University of Belgrade.
- *Teachers’ Affective Autonomy and Well-being*, EAQUALS.
- *Neuroscience of Stories*, İMBAT Akademi.
- *Cultural Context and the Neuroscience of Learning*, JALT.
- *How to be an Effective Online Learner*,  Özyeğin University.
- *Psychology and Pedagogy*, Özyeğin University.
- *Neuroscience and Pedagogy I*, Özyeğin University.
- *Neuroscience and Pedagogy II*, Özyeğin University.

